import { Price } from "@/types/pricing";

const pricingData: Price[] = [
  {
    bestOfSpecial: true,
    buttonText: "Start Your 3 Weeks + Extra Week Free",
    href: "https://momence.com/m/811964",
    id: 0,
    perX: "",
    popular: true,
    price: 79,
    subtitle: "3 Weeks + Extra Week Free of Unlimited Yoga",
    title: "New Client Intro",
  },
  {
    buttonText: "Book Class",
    href: "/schedule",
    id: 1,
    perX: "/class",
    price: 30,
    subtitle: "One yoga class",
    title: "Single Class",
  },
  {
    buttonText: "Join Unlimited Membership",
    href: "https://momence.com/m/137236",
    id: 2,
    perX: "/month",
    popular: true,
    price: 159,
    subtitle:
      "Recurring Monthly Unlimited Membership. Enjoy continuous, unlimited access to all scheduled classes, complimentary member workshops, and exclusive guest passes with a predictable monthly renewal",
    title: "Unlimited Member",
  },
  {
    buttonText: "Choose Limited Membership",
    href: "https://momence.com/m/136480",
    id: 3,
    perX: "/month",
    price: 99,
    subtitle: "4 classes per month",
    title: "Limited Member",
  },
  {
    buttonText: "Buy 10-Class Card",
    href: "https://momence.com/m/136479",
    id: 4,
    perX: "",
    price: 260,
    subtitle: "10 classes to be used over a one-year period",
    title: "10-Class Card",
  },
  {
    bestOfSpecial: true,
    buttonText: "Get Annual + Extra Month Free",
    href: "https://momence.com/m/811982",
    id: 5,
    perX: "/year",
    price: 1699,
    subtitle:
      "Our unlimited membership at an annual discount, plus an extra month free",
    title: "Annual + Extra Month Free",
  },
  {
    bestOfSpecial: true,
    buttonText: "Get Six-Month + Extra Month Free",
    href: "https://momence.com/m/811985",
    id: 6,
    perX: "",
    price: 899,
    subtitle: "Unlimited classes for 6 months, plus an extra month free",
    title: "Six-Month + Extra Month Free",
  },
  {
    bestOfSpecial: true,
    buttonText: "Buy 15-Class Card",
    href: "https://momence.com/m/464009",
    id: 8,
    perX: "",
    price: 300,
    subtitle: "15 classes valid through August 31st. No pauses or extensions",
    title: "Beat the Heat 15-Class Card",
  },
  {
    buttonText: "Get Traveler Pass",
    href: "https://momence.com/m/478019",
    id: 7,
    perX: "",
    price: 59,
    subtitle: "Unlimited classes for visitors for one week (one-time only)",
    title: "One Week Traveler's Pass",
  },
];

export default pricingData;
