import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions - Las Olas Yoga",
  description: "Terms and Conditions of using the Las Olas Yoga website.",
  // other metadata
};

const PrivacyPolicyPage = () => {
  return (
    <section className="m-5 mt-30 lg:m-30"><div><h2 className="text-sectiontitle3 text-center my-5">Terms and Conditions</h2>
    <div className="text-regular leading-10">
    <p><small>Thank you for visiting this Site, which is owned and operated by Las Olas Yoga. These Terms of Use govern your use of this Site.</small></p>
<p><small><strong>Your Acceptance of These Terms of Use</strong><br />
These Terms of Use apply to all users of this Site. By using this Site, you are agreeing to comply with, and be bound by, these Terms of Use. If you do not agree to these Terms of Use, you may not access or use this Site.</small></p>
<p><small><strong>Your Acceptance of Our Privacy Policy</strong><br />
By agreeing to these Terms of Use, you agree to the terms of our <a href="/privacy-policy"><strong>Privacy Policy</strong></a>, which is expressly incorporated herein. Before using this Site, please carefully review our Privacy Policy. All personal information provided to us as a result of your use of this Site will be handled in accordance with our Privacy Policy. To the extent there are inconsistencies between these Terms of Use and our Privacy Policy, these Terms of Use control.</small></p>
<p><small><strong>Your Consent to Other Agreements</strong><br />
When you sign up to use a special feature of this Site, you may be asked to agree to special terms governing your use of the special feature. In such cases, you may be asked to expressly consent to the special terms, for example, by checking a box or clicking on a button marked “I agree.” This type of agreement is known as a “click-through” agreement. If any of the terms of the click-through agreement are different than the terms of these Terms of Use, the terms of the click-through agreement will supplement or amend these Terms of Use, but only with respect to the matters governed by the “click-through agreement.”</small></p>
<p><small><strong>Ownership of this Site and its Content</strong><br />
This Site, including all its Content are protected under applicable intellectual property and other laws, including without limitation the laws of the United States and other countries. All Content and intellectual property rights therein are the property of Las Olas Yoga or the material is included with the permission of the rights owner and is protected pursuant to applicable copyright and trademark laws.</small></p>
<p><small>The presence of any Content on this Site does not constitute a waiver of any right in such Content. You do not acquire ownership rights to any such Content viewed through this Site. Except as otherwise provided herein, none of this Content may be used, copied, reproduced, distributed, republished, downloaded, modified, displayed, posted, or transmitted in any form or by any means, including, but not limited to, electronic, mechanical, photocopying, recording, or otherwise, without our express prior written permission.</small></p>
<p><small>Permission is hereby granted to the extent necessary to lawfully access and use this Site and to display, download, or print portions of this Site on a temporary basis and for your personal, educational, noncommercial use only, provided that you: (i) do not modify the Content; (ii) retain any and all copyright and other proprietary notices contained in the Content; and (iii) do not copy or post the Content on any network computer or broadcast the Content in any media.</small></p>
<p><small><strong>Trademarks</strong><br />
The Las Olas Yoga name and logos, all product and service names, all graphics, all button icons, and all trademarks, service marks and logos appearing within this Site, unless otherwise noted, are trademarks (whether registered or not), service marks and/or trade dress of Las Olas Yoga. All other trademarks, product names, company names, logos, service marks and/or trade dress mentioned, displayed, cited or otherwise indicated within this Site are the property of their respective owners. You are not authorized to display or use the Las Olas Yoga marks in any manner without our prior written permission. You are not authorized to display or use trademarks, product names, company names, logos, service marks and/or trade dress of other owners featured within this Site without the prior written permission of such owners. The use or misuse of the Las Olas Yoga marks or other trademarks, product names, company names, logos, service marks and/or trade dress or any other materials contained herein, except as permitted herein, is expressly prohibited.</small></p>
<p><small><strong>Your Obligations</strong></small><br />
<small>In consideration of your use of this Site, you agree that to the extent you provide personal information to Las Olas Yoga it will be true, accurate, current, and complete and that you will update all personal information as necessary.</small></p>
<p><small>To the extent you create an account through this Site, you understand and agree that any account you create, including your username and password, are personal to you and may not be used by anyone else. You are responsible for maintaining the confidentiality of your username and password and are fully responsible for all activities that occur under your username and password by you or by anyone else using your username and password, whether or not authorized by you. You agree to change your password immediately if you believe your password may have been compromised or used without authorization. You also agree to immediately inform us of any apparent breaches of security such as loss, theft or unauthorized disclosure or use of your username or password by contacting us using the information provided below.  Until we are so notified you will remain liable for any unauthorized use of your account.</small></p>
<p><small>You agree to use this Site in a manner consistent with any and all applicable rules and regulations. You agree not to upload or transmit through this Site any computer viruses, trojan horses, worms or anything else designed to interfere with, interrupt or disrupt the normal operating procedures of a computer. Any unauthorized modification, tampering or change of any information, or any interference with the availability of or access to this Site is strictly prohibited. We reserve all rights and remedies available to us.</small></p>
<p><small><strong>DISCLAIMERS</strong></small></p>
<p><small>WE MAKE NO REPRESENTATIONS OR WARRANTIES WITH RESPECT TO THIS SITE OR ITS CONTENT, OR ANY PRODUCT OR SERVICE AVAILABLE ON OR PROMOTED THROUGH THIS SITE. THIS SITE AND ALL OF ITS CONTENT (INCLUDING USER-GENERATED CONTENT) ARE PROVIDED ON AN “AS IS,” “AS AVAILABLE” BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY LAW, LAS OLAS YOGA, ITS AFFILIATES, AND THEIR SERVICE PROVIDERS AND LICENSORS DISCLAIM ANY AND ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, ARISING BY STATUTE, CUSTOM, COURSE OF DEALING, COURSE OF PERFORMANCE OR IN ANY OTHER WAY, WITH RESPECT TO THIS SITE, ITS CONTENT, AND ANY PRODUCTS OR SERVICES AVAILABLE OR PROMOTED THROUGH THIS SITE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, LAS OLAS YOGA, ITS AFFILIATES, AND THEIR SERVICE PROVIDERS AND LICENSORS DISCLAIM ALL REPRESENTATIONS AND WARRANTIES (A) OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE; (B) RELATING TO THE SECURITY OF THIS SITE; (C) THAT THE CONTENT OF THIS SITE IS ACCURATE, COMPLETE OR CURRENT; OR (D) THAT THIS SITE WILL OPERATE SECURELY OR WITHOUT INTERRUPTION OR ERROR.</small></p>
<p><small>WE DO NOT REPRESENT OR WARRANT THAT THIS SITE, ITS SERVERS, OR ANY TRANSMISSIONS SENT FROM US OR THROUGH THIS SITE WILL BE FREE OF ANY HARMFUL COMPONENTS (INCLUDING VIRUSES).</small></p>
<p><small>WE DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES AGAINST THE POSSIBILITY OF DELETION, MISDELIVERY OR FAILURE TO STORE COMMUNICATIONS, PERSONALIZED SETTINGS, OR OTHER DATA. YOU ACCEPT THAT OUR SHAREHOLDERS, OWNERS, OFFICERS, DIRECTORS, EMPLOYEES AND OTHER REPRESENTATIVES SHALL HAVE THE BENEFIT OF THIS CLAUSE.</small></p>
<p><small>APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OF CERTAIN WARRANTIES, SO ALL OR PART OF THIS DISCLAIMER OF WARRANTIES MAY NOT APPLY TO YOU.</small></p>
<p><small><strong>LIMITATION OF LIABILITY</strong></small><br />
<small>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAWS WE, ON BEHALF OF OUR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS, LICENSORS AND SERVICE PROVIDERS, EXCLUDE AND DISCLAIM LIABILITY FOR ANY LOSSES AND EXPENSES OF WHATEVER NATURE AND HOWSOEVER ARISING INCLUDING, WITHOUT LIMITATION, ANY DIRECT, INDIRECT, GENERAL, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES; LOSS OF USE; LOSS OF DATA; LOSS CAUSED BY A VIRUS; LOSS OF INCOME OR PROFIT; LOSS OF OR DAMAGE TO PROPERTY; CLAIMS OF THIRD PARTIES; OR OTHER LOSSES OF ANY KIND OR CHARACTER, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES, ARISING OUT OF OR IN CONNECTION WITH THE USE OF THIS SITE. YOU ASSUME TOTAL RESPONSIBILITY FOR ESTABLISHING SUCH PROCEDURES FOR DATA BACK UP AND VIRUS CHECKING AS YOU CONSIDER NECESSARY. THIS LIMITATION OF LIABILITY APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR ANY OTHER BASIS.</small></p>
<p><small>IF ANY PART OF THIS LIMITATION ON LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN THE AGGREGATE LIABILITY OF THE RELEASED PARTIES FOR LIABILITIES THAT OTHERWISE WOULD HAVE BEEN LIMITED SHALL NOT EXCEED TEN DOLLARS ($10.00).</small></p>
<p><small>This Site gives you specific legal rights and you may also have other rights which vary from country to country. Some jurisdictions do not allow certain kinds of limitations or exclusions of liability, so the limitations and exclusions set out in these Terms of Use may not apply to you. Other jurisdictions allow limitations and exclusions subject to certain conditions. In such a case the limitations and exclusions set out in these Terms of Use shall apply to the fullest extent permitted by the laws of such applicable jurisdictions. Your statutory rights as a consumer, if any, are not affected by these provisions, and we do not seek to exclude or limit liability for fraudulent misrepresentation.</small></p>
<p><small><strong>Links to Third-Party Websites</strong></small><br />
<small>This Site may provide links to other websites operated by third parties. Because we have no control over third-party websites, we are not responsible for the availability of those websites and do not endorse and are not responsible or liable for any content, advertising, services, products, or other materials on or available from such websites. Las Olas Yoga shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, advertising, services, products, or other materials on or available from such websites. These Terms of Use do not apply to your use of third-party websites; your use of such websites is subject to the terms and policies of the owner of such websites.</small></p>
<p><small><strong>Modification and Discontinuation</strong></small><br />
<small>We reserve the right at any time and from time-to-time to modify, edit, delete, suspend or discontinue, temporarily or permanently this Site (or any portion thereof) and/or the information, materials, products and/or services available through this Site (or any part thereof) with or without notice. You agree that we shall not be liable to you or to any third party for any such modification, editing, deletion, suspension or discontinuance of this Site.</small></p>
<p><small><strong>Waiver</strong></small><br />
<small>Our failure at any time to require performance of any provision of these Terms of Use or to exercise any right provided for herein will not be deemed a waiver of such provision or such right. All waivers must be in writing. Unless the written waiver contains an express statement to the contrary, no waiver by Las Olas Yoga of any breach of any provision of these Terms of Use or of any right provided for herein will be construed as a waiver of any continuing or succeeding breach of such provision, a waiver of the provision itself, or a waiver of any right under these Terms of Use.</small></p>
<p><small><strong>Severability</strong></small><br />
<small>If any provision of these Terms of Use is held by a court of competent jurisdiction to be contrary to law, such provision will be changed and interpreted so as to best accomplish the objectives of the original provision to the fullest extent allowed by law and the remaining provisions of these Terms of Use will remain in full force and effect.</small></p>
<p><small><strong>Governing Law, Jurisdiction and Venue</strong><br />
These Terms of Use will be governed under the laws of the State of Colorado without regard to its conflicts of law provisions. All actions or proceedings arising out of or relating to these Terms of Use will be venued exclusively in state or federal court in the City of Fort Lauderdale, Florida.  You hereby irrevocably consent and submit to the personal jurisdiction of said courts for all such purposes. However, we retain the right to bring legal proceedings in any jurisdiction where we believe that infringement of these Terms of Use is taking place or originating.</small></p>
<p><small><strong>Indemnity</strong><br />
You agree to indemnify and hold Las Olas Yoga, its subsidiaries, and affiliates, and their respective officers, agents, partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your use of this Site in violation of these Terms of Use and/or arising from a breach of these Terms of Use and/or any breach of your representations and warranties set forth above and/or if any material that you post using this Site causes us to be liable to another. We reserve the right to defend any such claim, and you agree to provide us with such reasonable cooperation and information as we may request.</small></p>
<p><small><strong>These Terms of Use May Change</strong><br />
These Terms of Use are current as of the effective date set forth above.  Las Olas Yoga reserves the right to change these Terms of Use from time to time consistent with applicable laws and principles. These changes will be effective as of the date we post the revised version on this Site.  Your continued use of this Site after we have posted the revised Terms of Use constitutes your agreement to be bound by the revised Terms of Use. If at any time you choose not to accept these Terms of Use, you should not use this Site.</small></p>
<p><small><strong>Entire Agreement</strong><br />
These Terms of Use (together with our Privacy Policy and any Privacy Notices or click-through agreements applicable to you) contain the entire understanding and agreement between you and Las Olas Yoga with respect to this Site and supersede all previous communications, negotiations, and agreements, whether oral, written, or electronic, between you and Las Olas Yoga with respect to this Site and your use of this Site.</small></p>
<p><small><strong>Definitions</strong><br />
<em>The term “Content”</em> refers to all of the software and code comprising or used to operate this Site, and all of the text, photographs, images, illustrations, graphics, sound recordings, video and audio-video clips, and other materials available on this Site,.</small></p>
<p><small><em>The term “including”</em> means “including, but not limited to.”</small></p>
<p><small><em>The term “Site” </em>refers to any website owned by Las Olas Yoga on which these terms of use are posted.</small></p>
<p><small><strong>Questions</strong><br />
If you have any questions about this site or these Terms of Use, please contact us via email or phone.<br />
Email: info@lasolas.yoga<br />
Phone: 954-372-5275</small></p>
    </div>
    </div></section>
    
  );
};

export default PrivacyPolicyPage;
